function [mother_idx] = detect_mother_image(list_of_images)
    % Detect the mother image in a list of images generated by DORIS 5.0.
    %
    % Output: the index of the mother image in list_of_images
    % Floris Heuff - 03/2018
    %
    % Adapted and functionized by Simon van Diepen - 02/2025

    % open doris_input.xml
    finput = fopen('doris_input.xml');
    temp = textscan(finput,'%s');
    doris_input = temp{1,1};
    fclose(finput);

    % extract the mother image (line 17 in the doris_input.xml)
    % TODO: this should not be a number, this will break if doris_input.xml is changed
    % The 14:end - 14 is needed to cut off <master_date> and </master_date>
    mother_image = doris_input{17}(14:end - 14);

    % Remove the dashes to get YYYYMMDD format
    mother_image(5) = [];
    mother_image(7) = [];

    % Find the mother index in list_of_images
    mother_idx = find(strcmp(mother_image,list_of_images));
end