version: '3'
services:
  caroline-dev:
    container_name: caroline-dev
    hostname: caroline-dev
    build:
      context: .
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./:/home/caroline/caroline
