version: '3'
services:

  caroline:
    container_name: caroline
    hostname: caroline
    build:
      context: .
      dockerfile: dockers/caroline/Dockerfile
    environment:
      CAROLINE_DB_HOST: ${CAROLINE_DB_HOST}
      CAROLINE_DB_NAME: ${CAROLINE_DB_NAME}
      CAROLINE_DB_USER: ${CAROLINE_DB_USER}
      CAROLINE_DB_PASSWORD: ${CAROLINE_DB_PASSWORD}
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  caroline-dev:
    container_name: caroline-dev
    hostname: caroline-dev
    build:
      context: .
      dockerfile: dockers/caroline-dev/Dockerfile
    environment:
      CAROLINE_DB_HOST: ${CAROLINE_DB_HOST}
      CAROLINE_DB_NAME: ${CAROLINE_DB_NAME}
      CAROLINE_DB_USER: ${CAROLINE_DB_USER}
      CAROLINE_DB_PASSWORD: ${CAROLINE_DB_PASSWORD}
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./:/home/caroline/src/caroline

  caroline-db:
    container_name: caroline-db
    hostname: caroline-db
    build:
      context: dockers/caroline-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CAROLINE_DB_NAME: ${CAROLINE_DB_NAME}
      CAROLINE_DB_USER: ${CAROLINE_DB_USER}
      CAROLINE_DB_PASSWORD: ${CAROLINE_DB_PASSWORD}
