# the default settings for merge_to_stack_python, running in the merge_to_stack_python job

merge_to_stack_python:
  general:
    AoI-name: "**AoI_name**"
    directory: '/project/caroline/Share/stacks_zarr'
    partition: 'normal'
    depsi_group-code-directory: '**CAROLINE_PLUGINS_DIRECTORY**/DePSI_group'
