# the default settings for DePSI-post, running in the mrm and depsi_post jobs

depsi_post:
  general:  # this job runs in the DePSI directories
    partition: 'normal'
    depsi_post-code-directory: '**CAROLINE_PLUGINS_DIRECTORY**/depsi_post_v2.1.4.0'
    cpxfiddle-directory: '**CAROLINE_PLUGINS_DIRECTORY**/cpxfiddle'

  depsi_post-settings:
    dlat: 0
    dlon: 0
    drdx: 0
    drdy: 0
    proj: 'rd'  # only works in the Netherlands!
    ref-dheight: 0
    posteriori-scale-factor: 1

    pred-model: [1, 3, 5]
    plot-mode: 'raster'  # 'raster', 'vector'
    do-plots: "{'defo', 'height', 'ens_coh', 'ens_coh_local', 'stc', 'amp_disp'}"
    fontsize: 16
    markersize: 1
    do-print: 1
    output-format: 1

    az0: []
    azN: []
    r0: []
    rN: []

    result: 1
    psc-selection: 1
    do-remove-filtered: 0
    which-sl-mask: 'apriori'

    shift-to-mean: 0
    new-ref-cn: []
    map-to-vert: 0

    output: "{'csv', 'csv_web_portal'}" #'shape', 'shape_conv', 'csv', 'matlab', 'csv_web_portal'

    defo-lim: []
    height-lim: []
    ens-coh-lim: 0.5
    ens-coh-local-lim: 0.6
    stc-lim: 8

    defo-clim: [-10, 10]
    height-clim: [-20, 20]
    ens-coh-clim: 0
    ens-coh-local-clim: 0
    stc-clim: 20
