name: rippl_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - utm 
  - requests 
  - numpy 
  - scipy 
  - scikit-image 
  - matplotlib 
  - fiona 
  - shapely 
  - cartopy 
  - pyproj 
  - lxml 
  - gdal