# plugin-definitions.yaml
# defines all necessary parameters for the installer to install the plugins
# **CAROLINE_PLUGINS_ARCHIVE_DIRECTORY** will be replaced by the installer with the actual plugins archive directory

github:
  depsi_post_v2.1.4.0:
    repo: "git@bitbucket.org:grsradartudelft/depsipost.git"
    tag: "v2.1.4.0"

  deinsar_v0.3.4:
    repo: "git@bitbucket.org:grsradartudelft/deinsar.git"
    tag: "v0.3.4"

  DePSI_group:
    repo: "git@github.com:TUDelftGeodesy/DePSI_group.git"
    branch: "caroline-clone-branch"

tarball:
  cpxfiddle: "**CAROLINE_PLUGINS_ARCHIVE_DIRECTORY**/cpxfiddle.tar.gz"
  depsi_v2.2.1.1: "**CAROLINE_PLUGINS_ARCHIVE_DIRECTORY**/depsi_v2.2.1.1.tar.gz"
  geocoding_v0.9: "**CAROLINE_PLUGINS_ARCHIVE_DIRECTORY**/geocoding_v0.9.tar.gz"
  rdnaptrans: "**CAROLINE_PLUGINS_ARCHIVE_DIRECTORY**/rdnaptrans.tar.gz"
