# plugin-definitions.yaml
# defines all necessary parameters for the installer to install the plugins
# **CAROLINE_PLUGINS_ARCHIVE_DIRECTORY** will be replaced by the installer with the actual plugins archive directory

github:
  parameter-files:
    repo: "git@github.com:TUDelftGeodesy/caroline-parameter-files.git"
    branch: "main"

  depsi_post_v2.1.4.0:
    repo: "git@bitbucket.org:grsradartudelft/depsipost.git"
    tag: "v2.1.4.1"

  deinsar_v0.3.4:
    repo: "git@bitbucket.org:grsradartudelft/deinsar.git"
    tag: "v0.3.4"

  DePSI:
    repo: "git@github.com:TUDelftGeodesy/DePSI.git"
    branch: "caroline-clone-branch"

  snap_toolbox:
    repo: "git@github.com:TUDelftGeodesy/snap-coregistration.git"
    branch: "caroline-clone-branch"

  cpxfiddle:
    repo: "git@github.com:TUDelftGeodesy/cpxfiddle.git"
    branch: "main"

  depsi_v2.2.1.1:
    repo: "git@github.com:TUDelftGeodesy/caroline-matlab-depsi.git"
    branch: "main"

  geocoding_v0.9:
    repo: "git@github.com:TUDelftGeodesy/caroline-matlab-geocoding.git"
    branch: "main"

  rdnaptrans:
    repo: "git@github.com:TUDelftGeodesy/caroline-matlab-RDNAPtrans.git"
    branch: "main"

tarball:
