---
# spider-config.yaml

directories:
  AOI_OVERVIEW_DIRECTORY: "/project/caroline/Share/caroline-aoi-extents"
  CAROLINE_CONTEXTUAL_DATA_DIRECTORY: "/project/caroline/Data/caroline-contextual-data"
  CAROLINE_INSTALL_DIRECTORY: "/project/caroline/Software/caroline"
  CAROLINE_PLUGINS_ARCHIVE_DIRECTORY: "/project/caroline/Software/archives/caroline_plugins"
  CAROLINE_PLUGINS_DIRECTORY: "/project/caroline/Software/caroline-plugins"
  CAROLINE_VIRTUAL_ENVIRONMENT_DIRECTORY: "/project/caroline/Software/venv/caroline"
  CAROLINE_WATER_MASK_DIRECTORY: "/project/caroline/Software/config/caroline-water-masks"
  CAROLINE_WORK_DIRECTORY: "/project/caroline/Software/run/caroline/work"
  FROZEN_PARAMETER_FILE_DIRECTORY: "/project/caroline/Software/run/caroline/frozen-parameter-files"
  PORTAL_UPLOAD_FLAG_DIRECTORY: "/project/caroline/Software/run/caroline/portal-upload-flags"
  ORBIT_DIRECTORY: "/project/caroline/Data/orbits"
  SLC_BASE_DIRECTORY: "/project/caroline/Data/radar_data/sentinel1"
  SLURM_OUTPUT_DIRECTORY: "/project/caroline/Software/run/caroline/slurm-output"
executables:
  SENDMAIL_EXECUTABLE: "/usr/sbin/sendmail"
run:
  RUN_MODE: "LIVE"
