function [mother_idx] = detect_mother_image(list_of_images,sensor)
    % Detect the mother image in a list of images generated by DORIS 5.0.
    %
    % Output: the index of the mother image in list_of_images
    % Floris Heuff - 03/2018
    %
    % Adapted and functionized by Simon van Diepen - 02/2025
    %
    % Support for other sensors by Simon van Diepen - 10/03/2025

    if strcmp(sensor,'S1')
        % open doris_input.xml
        finput = fopen('doris_input.xml');
        temp = textscan(finput,'%s');
        doris_input = temp{1,1};
        fclose(finput);

        % extract the mother image (line 17 in the doris_input.xml)
        % TODO: this should not be a number, this will break if doris_input.xml is changed
        % The 14:end - 14 is needed to cut off <master_date> and </master_date>
        mother_image = doris_input{17}(14:end - 14);

        % Remove the dashes to get YYYYMMDD format
        mother_image(5) = [];
        mother_image(7) = [];
    else
        % open run_deinsar.py
        finput = fopen('run_deinsar.py');
        temp = textscan(finput,'%s');
        deinsar_input = temp{1,1};
        fclose(finput);

        % extract the mother image (line 24 in run_deinsar.py)
        % TODO: this should not be a number, this will break if run_deinsar.py is changed
        % The 11:end - 1 is needed to cut off "master = '" and "'"
        mother_image = deinsar_input{24}(11:end - 1);
    end

    % Find the mother index in list_of_images
    mother_idx = find(strcmp(mother_image,list_of_images));
end